---
title: "Data Analysis"
author: "Himanshu"
date: "April 6, 2019"
output: html_document
---
```{r}
library(dplyr)
library(caret)
library(lubridate)
library(stringr)
library(tidyr)
library(corrplot)
library(ggcorrplot)
library(corrgram)
```

```{r}
# Loading data
df <- read.csv("FinalData.csv", header = TRUE)

```

```{r}
head(df)
```

```{r}
ncol(df)
str(df)
```
```{r}
#checking percentage of NA in data
tmp = sort(sapply(df, function(x) sum(length(which(is.na(x)))))/nrow(df),decreasing = TRUE)
            
```
```{r}
# removing variables with more than 50% of NA's

discard_column = names(tmp[tmp>0.5])
df1 = (df[,!(names(df) %in% discard_column)])

tmp = sort(sapply(df1, function(x) sum(length(which(is.na(x)))))/nrow(df1),decreasing = TRUE)
tmp[tmp>0]
```
```{r}
#earliest_cr_line still has some NA's, removing NA's containing records

df2 <- na.omit(df1, cols = c("earliest_cr_line"))
#sort(sapply(df2, function(x) sum(length(which(is.na(x)))))/nrow(df2),decreasing = TRUE)
```

```{r}
# correlation plot of all Numeric variables

numVars <- names(which(sapply(df2, is.numeric)))
catvars <- names(which(sapply(df2, is.factor)))
corrplot(cor(df2[,numVars],use="na.or.complete"))
```


```{r}
a <- cor(as.matrix(df2[,numVars]), use = "pairwise.complete.obs")
a[lower.tri(a,diag=TRUE)]=NA    #Prepare to drop duplicates and meaningless information
a <- as.data.frame(as.table(a)) #Turn into a 3-column table
a <- na.omit(a)                 #Get rid of the junk we flagged above
a <- a[order(-abs(a$Freq)),]    #Sort by highest correlation (whether +ve or -ve)
head(a, n = 20)
```
```{r}
# ID , member_id have perfect correlation
# loan_amount, funded amount and funded amount_inv have perfect correlation

```


```{r}
#It's not good idead to consider all numeric

numVars2 <- c("loan_amnt", "installment", "int_rate", "annual_inc", "dti", "open_acc",
             "pub_rec", "total_acc", "Compensation.of.employees", "Gross.domestic.product..GDP..by.state",
             "Quantity.indexes.for.real.GDP.by.state", "Real.GDP.by.state", "Subsidies", 
             "Taxes.on.production.and.imports", "Taxes.on.production.and.imports.less.subsidies")

corrgram(df2[,numVars2], order = TRUE, lower.panel = panel.shade, upper.panel = panel.pie, text.panel = panel.txt)

```
```{r}
library(DescTools)
Desc(df2$loan_amnt, main = "Loan amount distribution", plotit = TRUE)
```

```{r}
require(grid)
library(ggplot2)
library(gridExtra)
# The number of open credit lines in the borrower's credit file - open_acc
# The total number of credit lines currently in the borrower's credit file - total_acc

p1 <- ggplot(df2, aes(x = open_acc)) + geom_histogram(aes(fill = loan_status), position = "dodge", bins = 10)
p2<- ggplot(df2, aes(x = total_acc)) + geom_histogram(aes(fill = loan_status), position = "dodge", bins = 10)
grid.arrange(
  p1, p2,
    
  nrow = 1,
  top = "Credit Lines in Credit file of borrower",
  bottom = textGrob(
    " ",
    gp = gpar(fontface = 3, fontsize = 9),
    hjust = 1,
    x = 1
  )
)

# more number of credit lines are open for non defaulters 
```
```{r}
# Number of derogatory public records - pub_rec

ggplot(df2, aes(x = pub_rec)) + geom_histogram(aes(fill = loan_status), position = "dodge", bins = 10)
```
```{r}
p1 <- ggplot(df2, aes(x = loan_amnt)) + geom_histogram(aes(fill = loan_status), position = "dodge", bins = 10)
p2<- ggplot(df2, aes(x = installment)) + geom_histogram(aes(fill = loan_status), position = "dodge", bins = 10)
grid.arrange(
  p1, p2,
    
  nrow = 1,
  top = "Loan amount vs Installments",
  bottom = textGrob(
    "",
    gp = gpar(fontface = 3, fontsize = 9),
    hjust = 1,
    x = 1
  )
)

# however there is a 94% correlation between both Loan amount and installment, its plot does not look very similar
# hence we will keep both for further analysis
```

```{r}
# Analyzing categorical variables 
catvars
```
```{r}
Desc(df2$term, main = "Term", plotit = TRUE)
```


```{r}
Desc(df2$purpose, main = "Loan purposes", plotit = TRUE)

# most of the borrower took loan fro debt consolidation
```
```{r}
Desc(df2$application_type, main = "Application type", plotit = TRUE)

# only 1 % of the loan application type is Joint , It doesn't seem to be very good preictor 
```

```{r}
Desc(df2$grade, main = "Loan grades", plotit = TRUE)
```




```{r}
Desc(df2$emp_title, main = "Employee Title", plotit = TRUE)

# too many others values, should be removed
```


```{r}
Desc(df2$home_ownership, main = "Home Ownership", plotit = TRUE)
```

```{r}
# Removing unsed factors in home ownership
df2$home_ownership <- factor(df2$home_ownership)
table(df2$home_ownership)
```
```{r}

Desc(df2$initial_list_status, main = "initial list status", plotit = TRUE)
```
```{r}

Desc(df2$verification_status, main = "Verification status", plotit = TRUE)
```

```{r}
count <- df2 %>%
  group_by(loan_status, grade)%>%
  summarise(n=n())

library('sqldf')
sqlStr <- 
'
SELECT
loan_status, grade, count(*)
from df2
group by loan_status, grade
'
tmp1 <- sqldf(sqlStr)
tmp1


```

```{r}

gradeA <- (2665/144979)*100
gradeB <- (9781/244048)*100
gradeC <- (13131/232138)*100
gradeD <- (10972/128231)*100
gradeE <- (6602/63906)*100
gradeF <- (3098/19887)*100
gradeG <- (885/4593)*100

cat("Default rate for grade type A : ", gradeA)
cat("\nDefault rate for grade type B : ", gradeB)
cat("\nDefault rate for grade type C : ", gradeC)
cat("\nDefault rate for grade type D : ", gradeD)
cat("\nDefault rate for grade type E : ", gradeE)
cat("\nDefault rate for grade type F : ", gradeF)
cat("\nDefault rate for grade type G : ", gradeG)


```

```{r}
funded_amnt <-
  df2 %>%
  transmute(loan_amnt = loan_amnt, value = funded_amnt, 
              variable = "funded_amnt")

funded_amnt_inv <-
  df2 %>%
  transmute(loan_amnt = loan_amnt, value = funded_amnt_inv, 
              variable = "funded_amnt_inv")

plot_data <- rbind(funded_amnt, funded_amnt_inv)

ls()
```
```{r}
rm(list = ls()[grep("^funded", ls())])
```
```{r}
plot_data %>%
  ggplot(aes(x = loan_amnt, y = value)) +
  facet_wrap(~ variable, scales = "free_x", ncol = 3) +
  geom_point()
```
```{r}
# We can derive a few points from the plot:

# 1. there are instances when funded amount is smaller loan amount
# 2. there seems to be a number of loans where investment is smaller funded amount i.e. not the full loan is invested in
```


```{r}
df2 %>%
  select(int_rate, grade, issue_d) %>%
  group_by(grade, issue_d) %>%
  summarise(int_rate_mean = mean(int_rate, na.rm = TRUE)) %>%
  ggplot(aes(issue_d, int_rate_mean)) +
  geom_line(color= "dark green", size = 1) +
  facet_wrap(~ grade) +  xlab("Date issued")

#the mean interest rate is falling or relatively constant for high-rated clients
#the mean interest rate is increasing significantly for low-rated clients
```

```{r}

df2 %>%
  select(loan_amnt, grade, issue_d) %>%
  group_by(grade, issue_d) %>%
  summarise(loan_amnt_mean = mean(loan_amnt, na.rm = TRUE)) %>%
  ggplot(aes(issue_d, loan_amnt_mean)) +
  geom_line(color= "dark green", size = 1) +
  facet_wrap(~ grade) +  xlab("Date issued")

#the mean loan amount is increasing for all grades
#while high-rated clients have some mean loan amount volatility, it is much higher for low-rated clients

```
```{r}
# check if interest rates are dependent on grades
Desc(int_rate ~ grade, df2, digits = 1, main = "Interest rate by grade", plotit = TRUE)

# This is not a surprise higher the grade of loan higher the risk associated with it so high interest rate
```
```{r}
# Let's use term in analysisng interest rate by grade
library(scales)
give_count <- 
  stat_summary(fun.data = function(x) return(c(y = median(x)*1.06,
                                               label = length(x))),
               geom = "text")

give_mean <- 
  stat_summary(fun.y = mean, colour = "darkgreen", geom = "point", 
               shape = 18, size = 3, show.legend = FALSE)

df2 %>%
  ggplot(aes(grade, int_rate)) +
  geom_boxplot(fill = "white", colour = "darkblue", 
               outlier.colour = "red", outlier.shape = 1) +
  give_count +
  give_mean +
  scale_y_continuous(labels = comma) +
  labs(title="Interest Rate by Grade", x = "Grade", y = "Interest Rate \n") +
  facet_wrap(~ term)

#interest rate increases with grade increases
#a few loans seem to have an equally low interest rate independent of grade
#the spread of rates seems to increase with grade increase
#there tend to be more outliers on the lower end of the rate
#The 3-year term has a much higher number of high-rated borrowers while the 5-year term has a larger number in the low-rating grades
```
```{r}
# Let's look into it by subgrades

plot3 <- ggplot(df2, aes(x=int_rate, y=sub_grade)) + geom_point(aes(color=loan_status, alpha=0.4))
plot3 <- plot3 + theme_bw() + scale_fill_manual("Loan Status", values = c("red", "green")) +
  labs(y="Sub Grades", x="Interest Rates")
plot3

```

```{r}

# Ohh , Each subgrade has one interest rate with similar variables, this is due to human entry error
# let's delete these detected outliers

arg <- df2$int_rate==6 & df2$sub_grade=="F4"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="G1"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="F5"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="E5"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="E4"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="E3"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="E2"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="E1"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="D5"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="D4"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="D3"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="D2"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="D1"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="C5"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="C4"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="C3"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="C2"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="C1"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="B5"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="B4"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="B3"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="B2"
df2 <- subset(df2, arg==FALSE)

arg <- df2$int_rate==6 & df2$sub_grade=="B1"
df2 <- subset(df2, arg==FALSE)
```

```{r}
plot3 <- ggplot(df2, aes(x=int_rate, y=sub_grade)) + geom_point(aes(color=loan_status, alpha=0.4))
plot3 <- plot3 + theme_bw() + scale_fill_manual("Loan Status", values = c("red", "green")) +
  labs(y="Sub Grades", x="Interest Rates")
plot3

# this graph looks fine now
```
```{r}
plot(df2$Taxes.on.production.and.imports, df2$Taxes.on.production.and.imports.less.subsidies )

# highly correlated other than few outlying values 
# corr = 0.8264
# we can remove one of them for further processing
```


```{r}
# Variables to remove:

vars_to_remove <- 
  c("X", "id", "member_id", "funded_amnt", "funded_amnt_inv", "sub_grade", "emp_title", "url", "desc",
    "Taxes.on.production.and.imports.less.subsidies",
    "Gross.domestic.product..GDP..by.state")

df3 <- df2 %>% select(-one_of(vars_to_remove))
str(df3)
```

```{r}
write.csv(df3, file = "Data1.csv" )
```

